### ISSUE TITLE
[Feature] Quick actions button [move up, move down, remove] on tab items 

### ISSUE THREAD

**Issue by SHENG-X** [SHENG-X/simple-resume#21]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem. Currently, in order to move or delete a list item in the Work Experience, Education, Hornor, and Certification tab. It requires to expand the item first, which is not that convenient. 

**Describe the solution you'd like**
Add quick action buttons on the list item card 

**Describe alternatives you've considered**
Implement Drag/Drop functionalities to move items.

**Comment by BenChenDev** [comment]
Have you been working on it? I am planning to work on this problem from today.

**Comment by SHENG-X** [comment]
@BenChenDev not yet. I am still thinking about the design for it. Before you work on this item, please tell me how you plan to implement it or what it suppose to look like.
