### ISSUE TITLE
[Feature] List items with card like feeling

### ISSUE THREAD

**Issue by SHENG-X** [SHENG-X/simple-resume#22]
**Describe the solution you'd like**
List item with card like feeling with hover effect.

**Additional context**
<img width="320" alt="Screen Shot 2020-06-23 at 11 01 20 AM" src="https://user-images.githubusercontent.com/23110925/85438700-1c44e400-b541-11ea-8a51-82b00ef3eda8.png">

**Comment by BenChenDev** [comment]
I am on it.

**Comment by SHENG-X** [comment]
sure. Make sure you implement it on all list items

**Comment by BenChenDev** [comment]
Done.

**Comment by SHENG-X** [comment]
@BenChenDev can you do a pr then I can take a look at it, thanks.
