### ISSUE TITLE
[Feature] Keep add list item button on the top 

### ISSUE THREAD

**Issue by SHENG-X** [SHENG-X/simple-resume#23]
**Describe the solution you'd like**
Keep add button on top of the page, and make it clear for add. 

A new item should add and display on the top of the list

**Comment by SHENG-X** [comment]
<img width="319" alt="Screen Shot 2020-06-23 at 11 37 33 AM" src="https://user-images.githubusercontent.com/23110925/85443408-11d91900-b546-11ea-8183-811fdbcce776.png">

**Comment by SHENG-X** [comment]
<img width="391" alt="2020-06-23 at 12 46 PM" src="https://user-images.githubusercontent.com/23110925/85452535-d6434c80-b54f-11ea-9f9a-06de42873244.png">

**Comment by BenChenDev** [comment]
Working on it.
