### ISSUE TITLE
[Feature] Spell checker for summary/description textarea

### ISSUE THREAD

**Issue by SHENG-X** [SHENG-X/simple-resume#38]
**Describe the solution you'd like**
Add spell checker for summary/description textarea

**Comment by BenChenDev** [comment]
Working on this problem.

**Comment by SHENG-X** [comment]
sure. so there should be an extra button on the rich text area which you can click to turn spell checker on/off
<img width="365" alt="2020-06-29 at 5 45 PM" src="https://user-images.githubusercontent.com/23110925/86070182-db613980-ba30-11ea-85f0-15722e7d7359.png">
