### ISSUE TITLE
[Bug] Font choice not applying to all text

### ISSUE THREAD

**Issue by Cjkeenan** [SHENG-X/simple-resume#44]
**Describe the Bug**
When selecting a new font all text that is in a bulleted list, both levels do not apply the new font.

**Reproduction**
Steps to reproduce the behaviour:
1. Write a description with a bulleted list
2. Change font
3. See that that bulleted list does not change font

**Expected Behaviour**
All fonts on the resume should be the same style

**Screenshots**
![image](https://user-images.githubusercontent.com/10240016/86499563-cc37ff80-bd40-11ea-8ec2-b2b7d9bb8515.png)

**Desktop (please complete the following information):**
 - OS: MX Linux 19
 - Browser: Brave Browser

**Comment by SHENG-X** [comment]
@Cjkeenan Fixed.
