### ISSUE TITLE
[Bug] Saving PDF does not work

### ISSUE THREAD

**Issue by Cjkeenan** [SHENG-X/simple-resume#67]
**Describe the Bug**
When saving the resume either from the menu at the bottom of the resume or from the side panel, it generates a PDF that is not what is my resume, but rather just a bunch of white space and some of my theme colors at the bottom.

**Reproduction**
Steps to reproduce the behaviour:
1. Gengar template
2. Save via side panel or menu at the bottom of the resume.
3. Look at the downloaded file

**Expected Behaviour**
An accurate representation of the website's resume.

**Screenshots**
[colin_keenan_resume_9292020.pdf](https://github.com/SHENG-X/simple-resume/files/5301668/colin_keenan_resume_9292020.pdf)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge (Chromium version)

**Additional Context**
None.

**Comment by SHENG-X** [comment]
Hello @Cjkeenan, I tried your steps, but I cannot reproduce the bug. Can you do a hard reload on your browser, or try the print option next to the save button to see if it helps?

**Comment by Cjkeenan** [comment]
OK weird, I just tried it again and it works now. I was doing unconstrained so I did not want to use the print option, but now both printing and saving as PDF works, super weird.
