### ISSUE TITLE
[Bug] https://simpleresume.ca/ is not loading

### ISSUE THREAD

**Issue by rrjanbiah** [SHENG-X/simple-resume#74]
**Describe the Bug**

https://simpleresume.ca/ is not loading (due to SSL?)

**Reproduction**

**Additional Context**

Easy to promote it under https://news.ycombinator.com/item?id=28627374 as the posted applications are not that attractive when compared to https://simpleresume.ca/

**Comment by SHENG-X** [comment]
@rrjanbiah this issue should resolved by now, thanks

**Comment by rrjanbiah** [comment]
@SHENG-X Thanks for looking into it. But, please note that site is not up for me and when I checked with site status tools online (site up or down), all of them are reporting it is down.

**Comment by SHENG-X** [comment]
Hi @rrjanbiah, sorry,  there was one dns setting I forget to change. The site should be back online now. let me know if you have any other issue

**Comment by rrjanbiah** [comment]
@SHENG-X Thanks for checking. For me it is still down and other services also report it as down.. for example, https://www.isitdownrightnow.com/simpleresume.ca.html

**Comment by SHENG-X** [comment]
@rrjanbiah sorry,  I think it takes some time to propagate the dns changes. I checked the site you sent. I'm sure it is working now.

**Comment by rrjanbiah** [comment]
@SHENG-X Yes, up now. Looks great. Thanks
